# Cloudflare Pages Configuration
name = "nicklaus-vega-portfolio"
compatibility_date = "2024-05-13"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
output_directory = ".vercel/output/static"

[site]
bucket = ".vercel/output/static"

[env.production]
NODE_VERSION = "18.18.0" 